Add files via upload
The code has an error regarding Jupiter's API, here is the description:

SyntaxError: The requested module '/node_modules/.vite/deps/@jup-ag_api.js?v=836bb2d7' does not provide an export named 'Jupiter'